config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome_page#index'
  get 'welcome_page/index'
  resources :workers
  resources :jobs
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/job.rb
class Job < ApplicationRecord

  scope :ten_most_recent, -> { order(created_at: :desc).limit(10)}
    validates :description, presence: true
    validates :pricerange, presence: true
    validates :timerange, presence: true
    validates :contact, presence: true
  
  end

app/models/worker.rb
class Worker < ApplicationRecord

    validates :name, presence: true
    validates :specialty, presence: true
    validates :availability, presence: true
    validates :contact, presence: true
    before_save(:titleize_worker)

    private
    def titleize_worker
      self.name = self.name.titleize
    end
  end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/jobs_controller.rb
class JobsController < ApplicationController

  def index


    @jobs = Job.order(created_at: :desc)
    render :index
  end

  def new
    @job = Job.new
    render :new
  end

  def create
    @job = Job.new(job_params)
    if @job.save
      flash[:notice] = "Job successfully added!"
      redirect_to jobs_path
    else
      render :new
    end
  end

  def edit
    @job = Job.find(params[:id])
    flash[:notice] = "Job successfully edited!"
    render :edit
  end

  def show
    @job = Job.find(params[:id])
    render :show
  end

  def update
    @job = Job.find(params[:id])
    if @job.update(job_params)
      flash[:notice] = "Job successfully updated!"
      redirect_to jobs_path
    else
      render :edit
    end
  end

  def destroy
    @job = Job.find(params[:id])
    @job.destroy
    flash[:notice] = "Job successfully deleted!"
    redirect_to jobs_path
  end

  private
    def job_params
      params.require(:job).permit(:description, :pricerange, :timerange, :contact)
    end

end

app/controllers/welcome_page_controller.rb
class WelcomePageController < ApplicationController
  def index
    render :index
  end
end

app/controllers/workers_controller.rb
class WorkersController < ApplicationController

  def index


    @workers = Worker.order(created_at: :desc)
    render :index
  end

  def new
    @worker = Worker.new
    render :new
  end

  def create
    @worker = Worker.new(worker_params)
    if @worker.save
      flash[:notice] = "Worker successfully added!"
      redirect_to workers_path
    else
      render :new
    end
  end

  def edit
    @worker = Worker.find(params[:id])
    flash[:notice] = "Worker successfully edited!"
    render :edit
  end

  def show
    @worker = Worker.find(params[:id])
    render :show
  end

  def update
    @worker = Worker.find(params[:id])
    if @worker.update(worker_params)
      flash[:notice] = "Worker successfully updated!"
      redirect_to workers_path
    else
      render :edit
    end
  end

  def destroy
    @worker = Worker.find(params[:id])
    @worker.destroy
    flash[:notice] = "Worker successfully deleted!"
    redirect_to workers_path
  end

  private
    def worker_params
      params.require(:worker).permit(:name, :specialty, :availability, :contact)
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/jobs/edit.html.erb
<h1>Make changes to job information:</h1>

<%= render "layouts/job_form" %>


<div class="visible">
  <p><%= link_to "Return To Home Page", root_path %></p>
<div>

app/views/jobs/index.html.erb
<h1>Available Jobs</h1>



<% if @jobs.any? %>
<ul>
  <% @jobs.each do |job| %>
  <li><%= link_to job.description, job_path(job) %> <%=job.created_at%></li>
  <% end %>
</ul>
<% else %>
<p>There are no odd jobs yet.</p>
<% end %>

<div class="link">
<p><%= link_to "Add your oddjob", new_job_path %></p>

<p><%= link_to "Return To Home Page", root_path %></p>
</div>

app/views/jobs/new.html.erb
<h1>Add a new Product:</h1>

<%= render "layouts/job_form" %>
<div class="link">
<p><%= link_to "Return To Home Page", root_path %></p>
</div>

app/views/jobs/show.html.erb
<h1><%= @job.description %></h1>
<h3>Price Range: <%= @job.pricerange%></h3>
<h3>Time Range: <%= @job.timerange %></h3>
<h3>Contact: <%= @job.contact %></h3>


<div class="link">
<p><%= link_to "Edit", edit_job_path(@job) %></p>
<p><%= link_to "Delete", job_path(@job),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to jobs", jobs_path %></p>

<p><%= link_to "Return To Home Page", root_path %></p>
</div>

app/views/layouts/_errors.html.erb
<% if @job.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @job.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_job_errors.html.erb
<% if @job.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @job.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_job_form.html.erb
<%= render "layouts/job_errors", :object => @job %>

<div class="form">
<%= form_for @job do |f| %>
  <%= f.label :description %>
  <%= f.text_field :description %> <br>
  <br>
  <%= f.label :pricerange %>
  <%= f.text_field :pricerange %> <br>
  <br>
  <%= f.label :timerange %>
  <%= f.text_field :timerange %> <br>
  <br>
  <%= f.label :contact %>
  <%= f.text_field :contact %> <br>
  <br>
  <%= f.submit %>
<% end %>
</div>

app/views/layouts/_worker_errors.html.erb
<% if @worker.errors.any? %>
  <h3>Please fix these errors:</h3>
  <ul>
    <% @worker.errors.full_messages.each do |message| %>
      <li><%= message %></li>
    <% end %>
  </ul>
<% end %>

app/views/layouts/_worker_form.html.erb
<%= render "layouts/worker_errors", :object => @worker %>

<%= form_for @worker do |f| %>
  <%= f.label :name %>
  <%= f.text_field :name %>
  <%= f.label :specialty %>
  <%= f.text_field :specialty %>
  <%= f.label :availability %>
  <%= f.text_field :availability %>
  <%= f.label :contact %>
  <%= f.text_field :contact %>
  <%= f.submit %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OddjobMatchmaker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="container">
      <%= flash[:notice] %>
      <%= yield %>
    </div>
  </body>
</html>

app/views/welcome_page/index.html.erb
<div id="welcome">
  <h1>Welcome to The Oddjob Matchmaker</h1>
  <h2>A site for flexible people who have and/or want little (or big) jobs to do.</h2>

  <br><br><br><br>
  <p>         <%= link_to "Browse available jobs or add or your own!", jobs_path %>                <%= link_to "Look for good people, or get your name out there!", workers_path %>         </p>
<div>

app/views/workers/edit.html.erb
<h1>Make changes to worker information:</h1>

<%= render "layouts/worker_form" %>

<p><%= link_to "Return To Home Page", root_path %></p>

app/views/workers/index.html.erb
<h1>Available Workers:</h1>



<% if @workers.any? %>
<ul>
  <% @workers.each do |worker| %>
  <li><%= link_to worker.name, worker_path(worker) %><%=worker.created_at%></li>
  <% end %>
</ul>
<% else %>
<p>There are no workers yet.</p>
<% end %>


<p><%= link_to "Add your worker", new_worker_path %></p>

<p><%= link_to "Return To Home Page", root_path %></p>

app/views/workers/new.html.erb
<h1>Add a new Worker:</h1>

<%= render "layouts/worker_form" %>

<p><%= link_to "Return To Home Page", root_path %></p>

app/views/workers/show.html.erb
<h1><%= @worker.name %></h1>
<h3>Specialty: <%= @worker.specialty%></h3>
<h3>availability: <%= @worker.availability %></h3>
<h3>Contact: <%= @worker.contact %></h3>



<p><%= link_to "Edit", edit_worker_path(@worker) %></p>
<p><%= link_to "Delete", worker_path(@worker),
                         :data => {:confirm => "You sure?",
                                   :method => "delete"} %></p>

<p><%= link_to "Return to workers", workers_path %></p>

<p><%= link_to "Return To Home Page", root_path %></p>